### ISSUE TITLE
GitHub Marketplace: integrate diktat to the marketplace

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/diktat#1216]
# Diktat: Kotlin Static Analyzer
Need to create an action inside of GitHub marketplace for Diktat

# Default behaviour: 
1. [X] Downloads latest versions of ktlint and diktat to `GitHub.workspace/diktat`
2. [X] Recursively runs `./ktlint -R diktat.jar --disabled_rules=standard` on the default GitHub Actions root workspace: `GitHub.workspace`
3. [x] Stores the result into special directory with SARIF results
4. [x] Uploads SARIF results to GitHub

# Extra (non-default) options
1. [X] If you wish to customise the behaviour of diktat - you can simply put `diktat-analysis.yml` into the root path of your project and provide it to the Action with `config` option;
2. [X] If you wish to customise the path that leads to the project - you can simply provide `projectPath` option that will be relative to your GitHub workspace

**Comment by akuleshov7** [comment]
@icemachined if you would make a marketplace app for save-cloud - probably it would be easy to make the same for diktat

**Comment by akuleshov7** [comment]
@nulls also mentioned a very good idea: what if we will be very aggressive and will make `fixes` and commit them automatically

**Comment by akuleshov7** [comment]
Too many commits 

> We can also be less aggressive and propose changes as review comments, so that the user will be able to commit them using Github web UI

there will be too many commits, I guess...

**Comment by petertrr** [comment]
These suggestions [can be](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) committed as a single commit using 'Add suggestion to batch' feature

**Comment by 0x6675636b796f75676974687562** [comment]
Implemented: [saveourtool/benedikt](https://github.com/saveourtool/benedikt).
