### ISSUE TITLE
KtLint: migrate from `RuleSetProvider` to `RuleSetProviderV2`

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [saveourtool/diktat#1543]
_KtLint_ has introduced a major API change in the **0.47** release (see the [Release Notes](https://github.com/pinterest/ktlint/releases/tag/0.47.0)).

In particular, `RuleSet` and `RuleSetProvider` interfaces have been marked as deprecated, scheduled for removal in **0.48**.

We'll need to rewrite `DiktatRuleSetProvider` and `OrderedRuleSet` implementations accordingly.

* [X] Stop using any deprecated API #1570
   * [X] Create pinterest/ktlint#1710
* [x] stop extending `com.pinterest.ktlint.core.Rule`
* [x] leave `org.cqfn.diktat.ruleset.rules.DiktatRule` as is
* [x] introduce something like `RuleProxy` for running `org.cqfn.diktat.ruleset.rules.DiktatRule` as `com.pinterest.ktlint.core.Rule`
* [x] introduce something like `DiktatRuleProxyFactory` which creates `com.pinterest.ktlint.core.Rule` using `configRules` and creates `visitorModifiers` which are required for ordering.
   * Combine `DiktatRuleSetProviderV2` and `OrderedRuleSet`: Diktat's proxy to `RuleSetProviderV2` should keep ordering
   * Add `Rule.VisitorModifier` only when creating `RuleSetProviderV2` and it's only _KtLint_-specific. Preserve all logic related to creating _KtLint_ `Rule`'s in a single place.
* [ ] Change the `DiktatRuleSetProviderTest#check DiktatRuleSetProviderTest contain all rules` test which reads the source code of `Rule` and/or `DiktatRule` implementors to determine which rules are available at compile time.

**Comment by nulls** [comment]
A common suggestion:
- remove extending `com.pinterest.ktlint.core.Rule`
- leave `org.cqfn.diktat.ruleset.rules.DiktatRule` as is
- introduce something like RuleProxy for running `org.cqfn.diktat.ruleset.rules.DiktatRule` as `com.pinterest.ktlint.core.Rule`
- introduce something like DiktatRuleProxyFactory which creates `com.pinterest.ktlint.core.Rule` using `configRules` and creates visitorModifiers which are required for ordering

**Comment by petertrr** [comment]
> introduce something like RuleProxy
> introduce something like DiktatRuleProxyFactory

Sounds like a good idea. Not only will it help us adapt to changes in RuleSetProvider-related APIs (e.g. ordering) but will also decouple diktat from ktlint a bit and maybe even let us try Detekt as a framework
