### ISSUE TITLE
[EPIC] Wrap Ktlint

### ISSUE THREAD

**Issue by nulls** [saveourtool/diktat#1561]
Right now diktat is run by calling ktlint which calls diktat.
Upgrade of diktat in spotless requires upgrade of ktlint.

Need to add a wrapper for running of ktlint in diktat

- [x] #1564
- [x] #1796
- [x] #1563
- [x] _Create a wrapper to run diktat in gradle plugin_ #1655
- [x] ~~Make `diktat.jar` executable without ktlint~~ #1557
- [x] #1543
- [x] #1540
- [x] #1648

**Comment by nulls** [comment]
- [ ] Downgrade ktlint in master
- [ ] Create a wrapper to run diktat for spotless
- [ ] Create a wrapper to run diktat in maven plugin
- [ ] Create a wrapper to run diktat in gradle plugin
- [ ] Make `diktat.jar` executable without ktlint

**Comment by TWiStErRob** [comment]
Note: https://github.com/twitter/compose-rules/ project somehow managed to enable both Detekt and ktlint integration. I think you might be able to pull off the same with Spotless and ktlint (and maybe Detekt too, if you do, please add to https://detekt.dev/marketplace)

**Comment by TWiStErRob** [comment]
Off-topic tip: if you move the task list to the opening post, you'll get backlinks like this in children's header:
![image](https://user-images.githubusercontent.com/2906988/203155763-73a05e55-ddee-4cf0-b164-2b7a631de2b4.png)

**Comment by nulls** [comment]
> Note: https://github.com/twitter/compose-rules/ project somehow managed to enable both Detekt and ktlint integration. I think you might be able to pull off the same with Spotless and ktlint (and maybe Detekt too, if you do, please add to https://detekt.dev/marketplace)

Thanks, will look into it
